
create tablespace TBLSP_EMPLOYEE;

CREATE TABLE DWH_ODS.EMPLOYEE (
    TRANS_START TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    DWH_BUS_VALID_FROM DATE NOT NULL,
    DWH_BUS_VALID_TO DATE NOT NULL,
    DWH_SYS_VALID_FROM TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    DWH_SYS_VALID_TO TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END,
    PERIOD BUSINESS_TIME (DWH_BUS_VALID_FROM,DWH_BUS_VALID_TO),
    PERIOD SYSTEM_TIME (DWH_SYS_VALID_FROM,DWH_SYS_VALID_TO),
    DWH_SKEY BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DWH_PROCESS_ID BIGINT,
    EMPNO CHAR(6) NOT NULL,
    FIRSTNME VARCHAR(12) NOT NULL,
    MIDINIT CHAR(1),
    LASTNAME VARCHAR(15) NOT NULL,
    WORKDEPT CHAR(3),
    PHONENO CHAR(4),
    HIREDATE DATE,
    EDLEVEL SMALLINT NOT NULL,
    SEX CHAR(1),
    BIRTHDATE DATE,
    SALARY DECIMAL(9,2),
    BONUS DECIMAL(9,2),
    COMM DECIMAL(9,2)
)
IN TBLSP_EMPLOYEE;

create index DWH_ODS.EMPLOYEE_src_pk on DWH_ODS.EMPLOYEE(EMPNO);

create index DWH_ODS.EMPLOYEE_bustp on DWH_ODS.EMPLOYEE(DWH_BUS_VALID_FROM,DWH_BUS_VALID_TO);

create index DWH_ODS.EMPLOYEE_systp on DWH_ODS.EMPLOYEE(DWH_SYS_VALID_FROM,DWH_SYS_VALID_TO);

CREATE TABLE DWH_ODS.EMPLOYEE_HIST LIKE DWH_ODS.EMPLOYEE IN TBLSP_EMPLOYEE;

ALTER TABLE DWH_ODS.EMPLOYEE ADD VERSIONING USE HISTORY TABLE DWH_ODS.EMPLOYEE_HIST;

merge into DWH_ODS.EMPLOYEE t 
using (
    select * from DB2INST2.EMPLOYEE where SEX='M'
) s
on (
    t.EMPNO = s.EMPNO and
    t.DWH_BUS_VALID_TO > ?/*#1 business_time_start */
)
when not matched then
insert (
  DWH_BUS_VALID_FROM,
  DWH_BUS_VALID_TO,
  EMPNO,
  FIRSTNME,
  MIDINIT,
  LASTNAME,
  WORKDEPT,
  PHONENO,
  HIREDATE,
  EDLEVEL,
  SEX,
  BIRTHDATE,
  SALARY,
  BONUS,
  COMM,
  DWH_PROCESS_ID)
values (
  ?/*#2 business_time_start */,
  '9999-12-30',
  s.EMPNO,
  s.FIRSTNME,
  s.MIDINIT,
  s.LASTNAME,
  s.WORKDEPT,
  s.PHONENO,
  s.HIREDATE,
  s.EDLEVEL,
  s.SEX,
  s.BIRTHDATE,
  s.SALARY,
  s.BONUS,
  s.COMM,
  ?/*#3 DWH_PROCESS_ID*/
)
when matched and (
    (t.FIRSTNME <> s.FIRSTNME)
    or (t.MIDINIT <> s.MIDINIT)
    or (t.LASTNAME <> s.LASTNAME)
    or (t.WORKDEPT <> s.WORKDEPT)
    or (t.PHONENO <> s.PHONENO)
    or (t.HIREDATE <> s.HIREDATE)
    or (t.EDLEVEL <> s.EDLEVEL)
    or (t.SEX <> s.SEX)
    or (t.BIRTHDATE <> s.BIRTHDATE)
    or (t.SALARY <> s.SALARY)
    or (t.BONUS <> s.BONUS)
    or (t.COMM <> s.COMM)
) then
update
  for portion of business_time
      from ?/*#4 business_time_start */
      to ?/*#5 business_time_end */
set t.FIRSTNME = s.FIRSTNME,
    t.MIDINIT = s.MIDINIT,
    t.LASTNAME = s.LASTNAME,
    t.WORKDEPT = s.WORKDEPT,
    t.PHONENO = s.PHONENO,
    t.HIREDATE = s.HIREDATE,
    t.EDLEVEL = s.EDLEVEL,
    t.SEX = s.SEX,
    t.BIRTHDATE = s.BIRTHDATE,
    t.SALARY = s.SALARY,
    t.BONUS = s.BONUS,
    t.COMM = s.COMM,
    t.DWH_PROCESS_ID = ?/*#6 DWH_PROCESS_ID*/;
    
/*
0 prepare param:businessTimeStartValue value:Fri Jul 12 16:39:27 CEST 2013
1 prepare param:DWH_PROCESS_ID value:999
2 prepare param:businessTimeStartValue value:Fri Jul 12 16:39:27 CEST 2013
3 prepare param:businessTimeEndValue value:Fri Jul 12 16:39:27 CEST 2013
4 prepare param:DWH_PROCESS_ID value:999
*/

ALTER TABLE DWH_ODS.EMPLOYEE DROP VERSIONING;
