drop table DWH.DWTB_KV_BEST_ALLG_S1;
CREATE TABLE DWH.DWTB_KV_BEST_ALLG_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   SART1 VARCHAR(1),
   SART2 VARCHAR(1),
   PZ VARCHAR(1),
   VU_NR DECIMAL(5,0),
   BEDIENER_NR DECIMAL(5,0),
   BEDIENER_BEW_DAT DECIMAL(9,0),
   DAT_NEU DECIMAL(9,0),
   DAT_ALT DECIMAL(9,0),
   SB_NR DECIMAL(5,0),
   BEARB_ORT VARCHAR(1),
   LEIT_SATZ_M VARCHAR(1),
   OB_VU VARCHAR(1),
   NOTE VARCHAR(1),
   VERMITTLER DECIMAL(9,0),
   PROV_ART DECIMAL(3,0),
   PROV_PROZ_A DECIMAL(5,2),
   PROV_PROZ_F DECIMAL(5,2),
   DRUCK_SB VARCHAR(1),
   VN_KOPIE VARCHAR(1),
   GS_VERSAND VARCHAR(1),
   VM_VERSAND DECIMAL(9,0),
   UR_BEG DECIMAL(9,0),
   VS_NR_BEG DECIMAL(9,0),
   BEG_AEND DECIMAL(9,0),
   ABGDAT DECIMAL(9,0),
   ZW VARCHAR(1),
   FAELL_TT VARCHAR(2),
   FAELL_MM VARCHAR(2),
   ABL_J VARCHAR(4),
   RECHNUNGSSTOP_DAT DECIMAL(9,0),
   TARIF_ART DECIMAL(5,0),
   WKZ VARCHAR(3),
   KW DECIMAL(5,0),
   SF_ERST_EINST VARCHAR(2),
   TARGR VARCHAR(1),
   SONSTM VARCHAR(1),
   NATION VARCHAR(2),
   REGION_PLZ VARCHAR(5),
   HALTER_PLZ VARCHAR(5),
   HALTER_ORT VARCHAR(35),
   ZBN DECIMAL(4,0),
   ZBN_ART VARCHAR(1),
   ZBN_DAT DECIMAL(9,0),
   FI_ART VARCHAR(1),
   FI_LAUFZEIT VARCHAR(3),
   AMTL_KZ VARCHAR(12),
   AMTL_KZ_ART VARCHAR(1),
   BEWART_1 VARCHAR(2),
   BEWART_2 VARCHAR(2),
   BEWART_3 VARCHAR(2),
   ANZ_29C_ADR VARCHAR(1),
   EVTL_GUTH VARCHAR(1),
   KT_BER VARCHAR(1),
   RECHENERG VARCHAR(1),
   TB28_STAT VARCHAR(1),
   RUECKVERS VARCHAR(1),
   VS_ANZAHL VARCHAR(1),
   VS_STEUER VARCHAR(1),
   VS_KENNZ VARCHAR(1),
   OHNE_VST VARCHAR(1),
   A_B_JAHR VARCHAR(4),
   ART_VERW VARCHAR(30),
   GESWERT DECIMAL(7,0),
   MEHRWERT DECIMAL(7,0),
   WEGFSP VARCHAR(1),
   HAUPT_VS_NR DECIMAL(13,0),
   NEBEN_VS_NR DECIMAL(13,0),
   AZ_VN VARCHAR(30),
   AZ_VM VARCHAR(17),
   ANLAGEN VARCHAR(4),
   LEIT_SCH_EMPFEHLUNG VARCHAR(1),
   VORTRAG DECIMAL(11,2),
   BUCHUNG_NEU DECIMAL(11,2),
   AUS_FRAGMENT VARCHAR(1),
   EU_FSCHEIN VARCHAR(1),
   BD_KZ VARCHAR(1),
   PROZESS_ID VARCHAR(8),
   PROZESS_QUELLE DECIMAL(5,0),
   VERTRAG_BEARB_ORT VARCHAR(1),
   NUTZLAST DECIMAL(3,0),
   PLAETZE DECIMAL(3,0),
   RISCHL DECIMAL(3,0),
   HUBRAUM DECIMAL(5,0),
   HOECHST_GESCHW DECIMAL(3,0),
   UMSATZ DECIMAL(9,0),
   WECHSLER VARCHAR(1),
   DIENST_NR DECIMAL(3,0),
   MVERSN_NAME VARCHAR(35),
   MVERSN_VORNAME VARCHAR(35),
   HSN VARCHAR(4),
   TSN VARCHAR(3),
   AUSF VARCHAR(5),
   VN_ART VARCHAR(1),
   VN_ANREDE VARCHAR(1),
   VN_TYP VARCHAR(2),
   STELLUNG VARCHAR(2),
   BRANCHE VARCHAR(2),
   SF_TB DECIMAL(3,0),
   NUTZER_VN VARCHAR(1),
   NUTZER_GATTE VARCHAR(1),
   NUTZER_SOHN VARCHAR(1),
   NUTZER_TOCHTER VARCHAR(1),
   NUTZER_SO VARCHAR(1),
   NUTZER_ALTER VARCHAR(1),
   NUTZER_ALTER_M VARCHAR(2),
   NUTZER_ALTER_W VARCHAR(2),
   NUTZER_KREIS VARCHAR(1),
   JUENGSTES_FAM_GEBDAT DECIMAL(9,0),
   JAHRES_KM VARCHAR(2),
   KM_STAND VARCHAR(3),
   KM_STAND_AM DECIMAL(9,0),
   NUTZ_ART VARCHAR(1),
   ABSTELLPLATZ VARCHAR(1),
   GEBAEUDE VARCHAR(1),
   ERSTBESITZ VARCHAR(1),
   BERUF_VDS VARCHAR(2),
   BERUF_VHV VARCHAR(1),
   BERUFSGR_SCHL DECIMAL(5,0),
   FAHRGEBIET VARCHAR(2),
   GEFAHRGUT VARCHAR(1),
   ANHAENGER VARCHAR(1),
   AUFBAUART VARCHAR(2),
   NEUWERT DECIMAL(7,0),
   SAISON_BEGINN_MM VARCHAR(2),
   SAISON_ENDE_MM VARCHAR(2),
   DENO_KZ VARCHAR(1),
   GAP_KZ VARCHAR(1),
   VERBAND VARCHAR(3),
   BETRIEBSART VARCHAR(3),
   BEZ_AUFBAUART VARCHAR(30),
   FAG_KZ VARCHAR(1),
   FD_PD_KZ VARCHAR(1),
   FD_PD_H VARCHAR(2),
   FD_PD_H_VERS_SU VARCHAR(3),
   FD_PD_H_VERS_SU_MAX_VP VARCHAR(3),
   FD_PD_H_SB_B_SCHADEN DECIMAL(7,0),
   FD_PD_H_SB_B_VP DECIMAL(7,0),
   FD_PD_H_SB_P VARCHAR(2),
   FD_PD_H_SB_P_MIN_B DECIMAL(7,0),
   FD_PD_H_SB_P_MAX_B DECIMAL(7,0),
   FD_PD_H_SB_P_MAX_B_VP DECIMAL(7,0),
   PD_FRACHT_LOHN DECIMAL(9,0),
   VVG_MAKLER VARCHAR(1),
   VVG_VERZICHT VARCHAR(1),
   VVG_EMPFANG VARCHAR(1),
   VVG_FORM VARCHAR(1),
   VVG_V_INFO VARCHAR(10),
   VVG_MODELL VARCHAR(1),
   VVG_KZ VARCHAR(1),
   VVG_V_INFO_FEHLER VARCHAR(1),
   BF_NUTZER_KZ VARCHAR(1),
   BF_VN_KZ VARCHAR(1),
   HERKUNFT DECIMAL(9,0),
   SF_HKS VARCHAR(1),
   GJ_FK VARCHAR(2),
   VJ_FK VARCHAR(2),
   GJ_FK_VR VARCHAR(2),
   ZR VARCHAR(1),
   EVB_NR VARCHAR(7),
   EINGANGS_NR VARCHAR(20),
   EINGANGS_DAT DECIMAL(9,0),
   NUTZER_ALT_M_A VARCHAR(4),
   NUTZER_ALT_W_A VARCHAR(4),
   NUTZER_ALT_M_J VARCHAR(4),
   NUTZER_ALT_W_J VARCHAR(4),
   BF_M_A_KZ VARCHAR(1),
   BF_W_A_KZ VARCHAR(1),
   BF_M_J_KZ VARCHAR(1),
   BF_W_J_KZ VARCHAR(1),
   GEB_VN_DAT DECIMAL(9,0),
   FI_ABLAUF_DAT DECIMAL(9,0),
   ZA VARCHAR(1),
   BETRIEBS_AUSG VARCHAR(1),
   BONI_KZ VARCHAR(1),
   ZUG_KFZ_KZ VARCHAR(1),
   AMTL_KZ_ZUG_KFZ VARCHAR(12),
   NUTZER_ALT_J VARCHAR(4),
   BF_J_KZ VARCHAR(1),
   NUTZER_ALT_A VARCHAR(4),
   BF_A_KZ VARCHAR(1),
   FAHRTZWECK VARCHAR(1),
   VERMIETUNG VARCHAR(1),
   ENTG_PERS_BEF VARCHAR(1),
   VV_KUENDIGUNG VARCHAR(1),
   PROV990_DATUM VARCHAR(5),
   PROV990_ART VARCHAR(2),
   PROV990_PROZ VARCHAR(3),
   HERSTELLER VARCHAR(23),
   FGST_NR VARCHAR(18),
   FGST_NR_RESERVE VARCHAR(7),
   ZULGEW DECIMAL(5,0),
   ZULDAT DECIMAL(9,0),
   ERWERB_DAT DECIMAL(9,0),
   SF_BEG_DAT DECIMAL(9,0),
   SF_BEG_H VARCHAR(1),
   SF_BEG_F VARCHAR(1),
   SICH_ART VARCHAR(1),
   SICH_AZ VARCHAR(20),
   SICH_TERMINM VARCHAR(1),
   SICH_TERMIN DECIMAL(9,0),
   ALV_DAT DECIMAL(9,0),
   ALT_TARIF_ART DECIMAL(5,0),
   ALT_TARGR VARCHAR(1),
   VSV VARCHAR(1),
   VWB_ART VARCHAR(1),
   VWB_SB VARCHAR(1),
   VWB_ABGES DECIMAL(9,0),
   VWB_TERMIN DECIMAL(9,0),
   VWB_GRU VARCHAR(1),
   VWB_VU_NR DECIMAL(9,0),
   VWB_AZ_VU VARCHAR(20),
   VWB_KFZ_KZ_VU VARCHAR(12),
   ANZ_29C_ART VARCHAR(1),
   ANZ_29C_SB VARCHAR(1),
   ANZ_29C_ABGES DECIMAL(9,0),
   ANZ_29C_TERMIN DECIMAL(9,0),
   ANZ_29C_GRU VARCHAR(1),
   ANZ_29C_BEEND DECIMAL(9,0),
   FAELL_BEITR DECIMAL(9,2),
   INFO_DAT DECIMAL(9,0),
   AKT_GJ DECIMAL(4,0),
   LIEFER_DAT VARCHAR(10),
   H_JAHRES_NETTO_VJ DECIMAL(9,2),
   V_JAHRES_NETTO_VJ DECIMAL(9,2),
   T_JAHRES_NETTO_VJ DECIMAL(9,2),
   U_JAHRES_NETTO_VJ DECIMAL(9,2),
   VSV_JAHRES_NETTO_VJ DECIMAL(9,2),
   RS_JAHRES_NETTO_VJ DECIMAL(9,2),
   FU_JAHRES_NETTO_VJ DECIMAL(9,2),
   H_SF_PROZ_VJ DECIMAL(3,0),
   F_SF_PROZ_VJ DECIMAL(3,0),
   H_ALT_J_NETTO_VJ DECIMAL(9,2),
   V_ALT_J_NETTO_VJ DECIMAL(9,2),
   T_ALT_J_NETTO_VJ DECIMAL(9,2),
   U_ALT_J_NETTO_VJ DECIMAL(9,2),
   VSV_ALT_J_NETTO_VJ DECIMAL(9,2),
   RS_ALT_J_NETTO_VJ DECIMAL(9,2),
   FU_ALT_J_NETTO_VJ DECIMAL(9,2),
   H_JAHRES_NETTO_GJ DECIMAL(9,2),
   V_JAHRES_NETTO_GJ DECIMAL(9,2),
   T_JAHRES_NETTO_GJ DECIMAL(9,2),
   U_JAHRES_NETTO_GJ DECIMAL(9,2),
   VSV_JAHRES_NETTO_GJ DECIMAL(9,2),
   RS_JAHRES_NETTO_GJ DECIMAL(9,2),
   FU_JAHRES_NETTO_GJ DECIMAL(9,2),
   H_SF_PROZ_GJ DECIMAL(3,0),
   F_SF_PROZ_GJ DECIMAL(3,0),
   H_ALT_J_NETTO_GJ DECIMAL(9,2),
   V_ALT_J_NETTO_GJ DECIMAL(9,2),
   T_ALT_J_NETTO_GJ DECIMAL(9,2),
   U_ALT_J_NETTO_GJ DECIMAL(9,2),
   VSV_ALT_J_NETTO_GJ DECIMAL(9,2),
   RS_ALT_J_NETTO_GJ DECIMAL(9,2),
   FU_ALT_J_NETTO_GJ DECIMAL(9,2),
   H_ZWEIT_J_NETTO DECIMAL(9,2),
   V_ZWEIT_J_NETTO DECIMAL(9,2),
   H_ZWEIT_SF_PROZ DECIMAL(3,0),
   V_ZWEIT_SF_PROZ DECIMAL(3,0),
   H_REGIO_ART VARCHAR(3),
   H_TYPKL_ART DECIMAL(2,0),
   H_TARIF_DIM VARCHAR(3),
   H_STAERKE_TEXT VARCHAR(9),
   H_STAERKE_WERT DECIMAL(9,0),
   F_REGIO_ART VARCHAR(3),
   F_TYPKL_ART DECIMAL(2,0),
   F_TARIF_DIM VARCHAR(3),
   F_STAERKE_TEXT VARCHAR(9),
   F_STAERKE_WERT DECIMAL(9,0),
   ZBNR VARCHAR(4),
   ZWEITWAGEN VARCHAR(1),
   H_ANZ_TAGE DECIMAL(10,0),
   F_ANZ_TAGE DECIMAL(10,0),
   H_ZWEIT_J_NETTO_VSV DECIMAL(9,2),
   H_ZWEIT_J_NETTO_RS DECIMAL(9,2),
   H_ZWEIT_J_NETTO_FU DECIMAL(9,2),
   FVART DECIMAL(5,0),
   F_KASKO_TARBEG DECIMAL(9,0),
   F_KASKO_TARJ VARCHAR(4),
   F_BED_MM VARCHAR(2),
   F_BED_JJ VARCHAR(2),
   F_KASKO_MODELL DECIMAL(3,0),
   F_VN_ALTER VARCHAR(2),
   H_V_ART DECIMAL(5,0),
   H_BAUSTEIN_ART DECIMAL(5,0),
   H_DECK1 VARCHAR(1),
   H_DECK2_3 VARCHAR(2),
   H_DECK_SCHL_INT DECIMAL(5,0),
   H_BEITR DECIMAL(9,2),
   H_SB VARCHAR(1),
   H_SF_SFK VARCHAR(1),
   H_SF_RB_KZ VARCHAR(1),
   H_SF_RB_GJ DECIMAL(1,0),
   H_SF_GJ DECIMAL(3,0),
   H_SF_RSF_GJ DECIMAL(3,0),
   H_SF_GDV_GJ DECIMAL(3,0),
   H_ANZ_RUHETAGE_GJ DECIMAL(3,0),
   H_ANZ_SD_ART_1_GJ DECIMAL(1,0),
   H_ANZ_SD_ART_2_GJ DECIMAL(1,0),
   H_ANZ_SD_ART_3_GJ DECIMAL(1,0),
   H_SF_RB_VJ DECIMAL(1,0),
   H_SF_VJ DECIMAL(3,0),
   H_SF_RSF_VJ DECIMAL(3,0),
   H_SF_GDV_VJ DECIMAL(3,0),
   H_ANZ_RUHETAGE_VJ DECIMAL(3,0),
   H_ANZ_SD_ART_1_VJ DECIMAL(1,0),
   H_ANZ_SD_ART_2_VJ DECIMAL(1,0),
   H_ANZ_SD_ART_3_VJ DECIMAL(1,0),
   H_ABWSB DECIMAL(5,0),
   H_BED_MM VARCHAR(2),
   H_BED_JJ VARCHAR(2),
   H_TARBEG DECIMAL(9,0),
   H_TARJ VARCHAR(4),
   H_TARGR_V_ART VARCHAR(1),
   H_REGION VARCHAR(2),
   H_BEGAEND DECIMAL(9,0),
   H_VERS_SU VARCHAR(25),
   H_TYPKL VARCHAR(2),
   H_VSV_BAUSTEINART DECIMAL(5,0),
   H_VSV_DECK VARCHAR(1),
   H_VSV_DECK_SCHL_INT DECIMAL(5,0),
   H_VSV_BETR DECIMAL(5,2),
   H_RS_BAUSTEINART DECIMAL(5,0),
   H_RS_DECK VARCHAR(1),
   H_RS_DECK_SCHL_INT DECIMAL(5,0),
   H_RS_BETR DECIMAL(5,2),
   H_RS_NRV_STATUS VARCHAR(1),
   H_ABSCHL_PROV_BETR DECIMAL(9,2),
   H_ABSCHL_PROV_DATUM DECIMAL(9,0),
   H_KM_KL VARCHAR(1),
   H_FU_PLUS_KZ VARCHAR(1),
   H_FU_PLUS_BETR DECIMAL(5,2),
   H_AL_KZ VARCHAR(1),
   H_RB_KZ VARCHAR(1),
   H_ES_KZ VARCHAR(1),
   H_VN_ALTER VARCHAR(2),
   H_ALT_DAT DECIMAL(9,0),
   H_ALT_BEITR DECIMAL(9,2),
   H_ALT_TARGR_V_ART VARCHAR(1),
   H_ALT_REGION VARCHAR(2),
   H_ALT_TYPKL VARCHAR(2),
   H_ALT_BETR_FU DECIMAL(9,2),
   U_V_ART DECIMAL(5,0),
   U_BAUSTEIN_ART DECIMAL(5,0),
   U_DECK1 VARCHAR(1),
   U_DECK2_3 VARCHAR(2),
   U_DECK_SCHL_INT DECIMAL(5,0),
   U_BEITR DECIMAL(9,2),
   U_SB VARCHAR(1),
   U_BED_MM VARCHAR(2),
   U_BED_JJ VARCHAR(2),
   U_TARBEG DECIMAL(9,0),
   U_TARJ VARCHAR(4),
   U_BEGAEND DECIMAL(9,0),
   U_PL DECIMAL(3,0),
   U_TOD DECIMAL(7,0),
   U_INV DECIMAL(7,0),
   U_HEIL DECIMAL(5,0),
   U_TAG DECIMAL(3,0),
   U_PL_BERUF DECIMAL(1,0),
   U_PL_BEIF DECIMAL(1,0),
   U_TOD_B DECIMAL(7,0),
   U_INV_B DECIMAL(7,0),
   U_HEIL_B DECIMAL(5,0),
   U_TAG_B DECIMAL(3,0),
   U_ABSCHL_PROV_BETR DECIMAL(9,2),
   U_ABSCHL_PROV_DATUM DECIMAL(9,0),
   U_ALT_DAT DECIMAL(9,0),
   U_ALT_BEITR DECIMAL(9,2),
   SF_BEST_H_DAT DECIMAL(9,0),
   SF_BEST_H_VU_NR DECIMAL(9,0),
   SF_BEST_H_GRU VARCHAR(1),
   SF_BEST_VK_DAT DECIMAL(9,0),
   SF_BEST_VK_VUNR DECIMAL(9,0),
   SF_BEST_VK_GRU VARCHAR(1),
   LETZTE_POST_DAT decimal(9,0),
   ERHOBEN_BIS_DAT decimal(9,0),
   MASCHHISTORIE varchar(2),
   CHECKSUM varchar(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_ALLG_S1_HIST LIKE DWH.DWTB_KV_BEST_ALLG_S1;
ALTER TABLE DWH.DWTB_KV_BEST_ALLG_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_ALLG_S1_HIST;

drop table DWH.DWTB_KV_BEST_FAHRZEUG_DECKUNG_S1;
CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_DECKUNG_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   F_BAUSTEIN_ART DECIMAL(5,0),
   F_DECK1 VARCHAR(1),
   F_DECK2_3 VARCHAR(2),
   F_DECK_SCHL_INT DECIMAL(5,0),
   F_BEITR DECIMAL(9,2),
   F_SB VARCHAR(1),
   F_SF_SFK VARCHAR(1),
   F_SF_RB_KZ VARCHAR(1),
   F_SF_RB_GJ DECIMAL(1,0),
   F_SF_GJ DECIMAL(3,0),
   F_SF_RSF_GJ DECIMAL(3,0),
   F_SF_GDV_GJ DECIMAL(3,0),
   F_ANZ_RUHETAGE_GJ DECIMAL(3,0),
   F_ANZ_SD_ART_1_GJ DECIMAL(1,0),
   F_ANZ_SD_ART_2_GJ DECIMAL(1,0),
   F_ANZ_SD_ART_3_GJ DECIMAL(1,0),
   F_SF_RB_VJ DECIMAL(1,0),
   F_SF_VJ DECIMAL(3,0),
   F_SF_RSF_VJ DECIMAL(3,0),
   F_SF_GDV_VJ DECIMAL(3,0),
   F_ANZ_RUHETAGE_VJ DECIMAL(3,0),
   F_ANZ_SD_ART_1_VJ DECIMAL(1,0),
   F_ANZ_SD_ART_2_VJ DECIMAL(1,0),
   F_ANZ_SD_ART_3_VJ DECIMAL(1,0),
   F_ABWSB_1 DECIMAL(5,0),
   F_ABWSB_2 DECIMAL(5,0),
   F_TYPKL VARCHAR(2),
   F_TARGR_V_ART VARCHAR(1),
   F_REGION VARCHAR(2),
   F_BEGAEND DECIMAL(9,0),
   F_ABSCHL_PROV_BETR DECIMAL(9,2),
   F_ABSCHL_PROV_DATUM DECIMAL(9,0),
   F_KASKO_KM_KL VARCHAR(1),
   F_ED_KZ VARCHAR(1),
   F_KS_KZ VARCHAR(1),
   F_BB_KZ VARCHAR(1),
   F_ZB_KZ VARCHAR(1),
   F_RB_KZ VARCHAR(1),
   F_IH_KZ VARCHAR(1),
   F_ALT_BAUSTEIN_ART DECIMAL(5,0),
   F_ALT_DAT DECIMAL(9,0),
   F_ALT_BEITR DECIMAL(9,2),
   F_ALT_TARGR_V_ART VARCHAR(1),
   F_ALT_REGION VARCHAR(2),
   F_ALT_TYPKL VARCHAR(2),
   F_DECK_POS integer,
   F_ALT_V_ART DECIMAL(5,0),
   F_ALT_KASKO_MODELL DECIMAL(3,0),
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_DECKUNG_S1_HIST LIKE DWH.DWTB_KV_BEST_FAHRZEUG_DECKUNG_S1;
ALTER TABLE DWH.DWTB_KV_BEST_FAHRZEUG_DECKUNG_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_FAHRZEUG_DECKUNG_S1_HIST;

drop table DWH.DWTB_KV_BEST_FAHRZEUG_MWERT_S1;
CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_MWERT_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   F_MW_TEXT VARCHAR(15),
   F_MW_WERT DECIMAL(7,0),
   F_MW_BAUSTEIN_ART DECIMAL(5,0),
   F_MW_ABW VARCHAR(1),
   F_MW_PROZ DECIMAL(5,2),
   F_MW_BAUSTEIN_ART_1 DECIMAL(5,0),
   F_MW_ABW_1 VARCHAR(1),
   F_MW_PROZ_1 DECIMAL(5,2),
   F_MW_BAUSTEIN_ART_2 DECIMAL(5,0),
   F_MW_ABW_2 VARCHAR(1),
   F_MW_PROZ_2 DECIMAL(5,2),
   F_MW_BAUSTEIN_ART_3 DECIMAL(5,0),
   F_MW_ABW_3 VARCHAR(1),
   F_MW_PROZ_3 DECIMAL(5,2),
   FMW_POS integer,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_MWERT_S1_HIST LIKE DWH.DWTB_KV_BEST_FAHRZEUG_MWERT_S1;
ALTER TABLE DWH.DWTB_KV_BEST_FAHRZEUG_MWERT_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_FAHRZEUG_MWERT_S1_HIST;

drop table DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_ALT_S1;
CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_ALT_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   F_ALT_ZUNA_ART VARCHAR(2),
   F_ALT_ZUNA_PBK VARCHAR(1),
   F_ALT_ZUNA_BETR DECIMAL(9,2),
   F_ALT_ZUNA_POS integer,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_ALT_S1_HIST LIKE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_ALT_S1;
ALTER TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_ALT_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_ALT_S1_HIST;

drop table DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_S1;
CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   F_ZUNA_BAUSTEIN_ART DECIMAL(5,0),
   F_ZUNA_ART VARCHAR(2),
   F_ZUNA_PBK VARCHAR(1),
   F_ZUNA_BETR DECIMAL(9,2),
   F_ZUNA_SCHL DECIMAL(5,0),
   F_ZUNA_SCHL_LFD_NR DECIMAL(5,0),
   F_ZUNA_POS integer,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_S1_HIST LIKE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_S1;
ALTER TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_FAHRZEUG_ZUNA_S1_HIST;

drop table DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_ALT_S1;
CREATE TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_ALT_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   H_ALT_ZUNA_ART VARCHAR(2),
   H_ALT_ZUNA_PBK VARCHAR(1),
   H_ALT_ZUNA_BETR DECIMAL(9,2),
   H_ALT_ZUNA_POS integer,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_ALT_S1_HIST LIKE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_ALT_S1;
ALTER TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_ALT_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_ALT_S1_HIST;

drop table DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_S1;
CREATE TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   H_ZUNA_ART VARCHAR(2),
   H_ZUNA_PBK VARCHAR(1),
   H_ZUNA_BETR DECIMAL(9,2),
   H_ZUNA_SCHL DECIMAL(5,0),
   H_ZUNA_SCHL_LFD_NR DECIMAL(5,0),
   H_ZUNA_POS integer,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_S1_HIST LIKE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_S1;
ALTER TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_HAFTPFLICHT_ZUNA_S1_HIST;

drop table DWH.DWTB_KV_BEST_UNFALL_ZUNA_ALT_S1;
CREATE TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_ALT_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
    -- value columns
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   U_ALT_ZUNA_ART VARCHAR(2),
   U_ALT_ZUNA_PBK VARCHAR(1),
   U_ALT_ZUNA_BETR DECIMAL(9,2),
   U_ALT_ZUNA_POS integer not null,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_ALT_S1_HIST LIKE DWH.DWTB_KV_BEST_UNFALL_ZUNA_ALT_S1;
ALTER TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_ALT_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_ALT_S1_HIST;

drop table DWH.DWTB_KV_BEST_UNFALL_ZUNA_S1;
CREATE TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_S1 (
    TRANS_START                    TIMESTAMP(12)  GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    GUELTIG_VON                    DATE           NOT NULL,
    GUELTIG_BIS                    DATE           NOT NULL,
    AEND_AM                        TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN,
    ERSETZT_AM                     TIMESTAMP(12)  NOT NULL GENERATED ALWAYS AS ROW END,
    -- value columns
    PROZESS_ID_ANLAGE              BIGINT         NOT NULL,
    PROZESS_ID_AEND                BIGINT,
   VSNR DECIMAL(13,0) not null,
   VSNR_DAT DECIMAL(9,0) not null,
   U_ZUNA_ART VARCHAR(2),
   U_ZUNA_PBK VARCHAR(1),
   U_ZUNA_BETR DECIMAL(9,2),
   U_ZUNA_SCHL DECIMAL(5,0),
   U_ZUNA_SCHL_LFD_NR DECIMAL(5,0),
   U_ZUNA_POS integer not null,
   CHECKSUM VARCHAR(255),
    -- IBM SCD config
    PERIOD SYSTEM_TIME (AEND_AM, ERSETZT_AM),
    PERIOD BUSINESS_TIME (GUELTIG_VON, GUELTIG_BIS));

CREATE TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_S1_HIST LIKE DWH.DWTB_KV_BEST_UNFALL_ZUNA_S1;
ALTER TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_S1 ADD VERSIONING USE HISTORY TABLE DWH.DWTB_KV_BEST_UNFALL_ZUNA_S1_HIST;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                